#!/bin/bash
set -e

BMPMAS="/etc/bearmail/postfix/master.cf"
BMPMAI="/etc/bearmail/postfix/main.cf"
BMPTRA="/etc/bearmail/postfix/bearmail-transport"
CVDIR="/etc/clamav/"

if [ "$1" = "configure" ]; then
  # check if bearmail was activate
  if [ -L /etc/mailmap ] ; then
    bearmail-switch suspend
    BEARMAIL_ON="1"
  fi

  # configure master.cf :
  if [ ! "$(grep "^## bearmail-antivirus - EOC" $BMPMAS)" ]; then
    sed -e '\!^## bearmail-antivirus$!a\
bearmail_scan      unix  -       -       n       -       16      smtp\
  -o smtp_send_xforward_command=yes\
\
# clamsmtp outgoing port\
127.0.0.1:10026 inet  n -       -       -       16      smtpd\
  -o content_filter=\
  -o receive_override_options=no_unknown_recipient_checks,no_header_body_checks\
  -o smtpd_helo_restrictions=\
  -o smtpd_client_restrictions=\
  -o smtpd_sender_restrictions=\
  -o smtpd_recipient_restrictions=permit_mynetworks,reject\
  -o mynetworks_style=host\
  -o smtpd_authorized_xforward_hosts=127.0.0.0/8\
\
# re-send viruses when asked to : \
bearmail_virus-sender    unix    -       n       n       -       10      pipe\
  flags= user=clamsmtp argv=/usr/lib/bearmail/bearmail-virus_send $sender\
## bearmail-antivirus - EOC
' -i $BMPMAS
    sed '/./,/^$/!d' -i $BMPMAS
  fi

  # configure main.cf
  if [ ! "$(grep "^# bearmail-antivirus - EOC" $BMPMAI)" ]; then
    sed -e '\!^# bearmail-antivirus$!a\
content_filter = bearmail_scan:[127.0.0.1]:10025\
# bearmail-antivirus - EOC\
' -i $BMPMAI
    sed '/./,/^$/!d' -i $BMPMAI
  fi

  # configure transport
  if [ ! "$(grep "bearmail_virus-sender" $BMPTRA)" ]; then
    MY_DOMAIN=`cat /etc/mailname`
    echo "virus@$MY_DOMAIN bearmail_virus-sender:" >> $BMPTRA
    echo "Warning: using $MY_DOMAIN for bearmail_virus-sender"
  fi

  # restart bearmail if needed
  if [ "$BEARMAIL_ON" ] ; then
    echo "Restarting bearmail"
    bearmail-switch on
  fi
fi
#DEBHELPER#
