#!/bin/bash
set -e

BMPMAS="/etc/bearmail/postfix/master.cf"
BMPMAI="/etc/bearmail/postfix/main.cf"
BMPAL="/etc/aliases"
CVDIR="/etc/clamav/"
BMCSD="/var/spool/clamsmtp-bearmail"
BMCRD="/var/run/clamsmtp-bearmail"

if [ "$1" = "configure" ]; then

  # create spool and run dir for clamsmtpd
  [ -d "$BMCSD" ] || install -m 750 -o bearmail -g bearmail -d $BMCSD
  [ -d "$BMCRD" ] || install -m 755 -o bearmail -g bearmail -d $BMCRD

  # adding bearmail to clamav and restarting clamav
  invoke-rc.d clamsmtp stop
  adduser clamav bearmail
  invoke-rc.d clamav-daemon stop
  invoke-rc.d clamav-daemon start
 
  # check if bearmail was activate
  if [ -L /etc/mailmap ] ; then
    bearmail-switch suspend
    BEARMAIL_ON="1"
  fi
 
  # configure master.cf :
  if [ ! "$(grep "^## bearmail-antivirus - EOC" $BMPMAS)" ]; then
    sed -e '\!^## bearmail-antivirus$!a\
bearmail_scan      unix  -       -       n       -       16      smtp\
  -o smtp_send_xforward_command=yes\
\
# clamsmtp outgoing port\
127.0.0.1:10026 inet  n -       -       -       16      smtpd\
  -o content_filter=\
  -o receive_override_options=no_unknown_recipient_checks,no_header_body_checks\
  -o smtpd_helo_restrictions=\
  -o smtpd_client_restrictions=\
  -o smtpd_sender_restrictions=\
  -o smtpd_recipient_restrictions=permit_mynetworks,reject\
  -o mynetworks_style=host\
  -o smtpd_authorized_xforward_hosts=127.0.0.0/8\
\
## bearmail-antivirus - EOC
' -i $BMPMAS
    sed '/./,/^$/!d' -i $BMPMAS
  fi

  # configure main.cf
  if [ ! "$(grep "^# bearmail-antivirus - EOC" $BMPMAI)" ]; then
    sed -e '\!^# bearmail-antivirus$!a\
content_filter = bearmail_scan:[127.0.0.1]:10025\
# bearmail-antivirus - EOC\
' -i $BMPMAI
    sed '/./,/^$/!d' -i $BMPMAI
  fi

  # configure aliases
  if [ ! "$(grep "^# bearmail-antivirus" $BMPAL)" ]; then
    cat >> $BMPAL << EOF
# bearmail-antivirus
virus: |/usr/lib/bearmail/bearmail-virus_send
EOF
    newaliases
  fi

  # restart bearmail if needed
  if [ "$BEARMAIL_ON" ] ; then
    echo "Restarting bearmail"
    bearmail-switch on
  fi
fi
#DEBHELPER#
