#!/bin/sh -e

BMPAL="/etc/aliases"
BMPMAS="/etc/bearmail/postfix/master.cf"
BMPMAI="/etc/bearmail/postfix/main.cf"
BMPTRA="/etc/bearmail/postfix/bearmail-transport"

set -e
remove_section() {
        # check if bearmail was activate
        if [ -L /etc/mailmap ] ; then
          bearmail-switch suspend
          BEARMAIL_ON="1"
        fi
        
        # configure master.cf :
        if [ "$(grep "^## bearmail-antivirus - EOC" $BMPMAS)" ]; then
          sed "/## bearmail-antivirus$/,\
               /## bearmail-antivirus - EOC/d" \
              -i $BMPMAS
          sed -e '\!^## bearmail-antispam$!i\
\
## bearmail-antivirus' -i $BMPMAS
          sed '/./,/^$/!d' -i $BMPMAS
        fi
        
        # configure main.cf
        if [ "$(grep "^# bearmail-antivirus - EOC" $BMPMAI)" ]; then
          sed "/# bearmail-antivirus$/,\
               /# bearmail-antivirus - EOC/d" \
              -i $BMPMAI
          sed -e '\!^# bearmail-antispam$!i\
\
# bearmail-antivirus' -i $BMPMAI
          sed '/./,/^$/!d' -i $BMPMAI
        fi

        # configure transport
        if [ "$(grep "^# bearmail-antivirus" $BMPAL)" ]; then
          sed "/^# bearmail-antivirus/d" -i $BMPAL
          sed "/bearmail-virus_send/d" -i $BMPAL
        fi

        # restart bearmail if needed
        if [ "$BEARMAIL_ON" -eq "1" ] ; then
          echo "Restarting bearmail"
          bearmail-switch on
        fi
}


case "$1" in
    upgrade)
        ;;
    deconfigure)
        ;;
    remove)
        remove_section ;;
    failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1 ;;
esac
#DEBHELPER#
exit 0
