Document: bearmail
Title: Debian bearmail Manual
Author: <insert document author here>
Abstract: This manual describes what bearmail is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bearmail/bearmail.sgml.gz

Format: postscript
Files: /usr/share/doc/bearmail/bearmail.ps.gz

Format: text
Files: /usr/share/doc/bearmail/bearmail.text.gz

Format: HTML
Index: /usr/share/doc/bearmail/html/index.html
Files: /usr/share/doc/bearmail/html/*.html

  
