#!/bin/bash
set -e

BMPMAI="/etc/bearmail/postfix/main.cf"

if [ "$1" = "configure" ]; then

  # create socket dir for clamav-milter in postfix spool
  mkdir -p /var/spool/postfix/var/run/clamav
  chown postfix /var/spool/postfix/var /var/spool/postfix/var/run
  chown clamav /var/spool/postfix/var/run/clamav

  # chown/chmod for freshclam.conf
  chown clamav:adm /etc/bearmail/clamav/freshclam.conf
  chmod 444 /etc/bearmail/clamav/freshclam.conf


  # check if bearmail was activate
  if [ -L /etc/mailmap ] ; then
    bearmail-switch suspend
    BEARMAIL_ON="1"
  fi
 
  # configure main.cf
  if [ ! "$(grep "^smtpd_milters" $BMPMAI)" ]; then
    echo "smtpd_milters = " >> $BMPMAI
  fi
  if [ ! "$(grep "unix:/var/run/clamav/clamav-milter.ctl" $BMPMAI)" ]; then
    sed -e '\!^smtpd_milters = $!a\
  unix:/var/run/clamav/clamav-milter.ctl' -i $BMPMAI
  fi
  if [ ! "$(grep "^milter_connect_macros =" $BMPMAI)" ]; then
   echo "milter_connect_macros = j" >> $BMPMAI
  fi
  if [ ! "$(grep "^milter_protocol =" $BMPMAI)" ]; then
    echo "milter_protocol = 3" >> $BMPMAI
  fi

  # restart bearmail if needed
  if [ "$BEARMAIL_ON" ] ; then
    echo "Restarting bearmail"
    bearmail-switch on
  fi
fi
#DEBHELPER#
