#!/bin/sh -e

BMPMAI="/etc/bearmail/postfix/main.cf"

set -e
remove_section() {
        # check if bearmail was activate
        if [ -L /etc/mailmap ] ; then
          bearmail-switch suspend
          BEARMAIL_ON="1"
        fi
        
        # configure master.cf :
        sed '/unix:\/var\/run\/clamav\/clamav-milter.ctl/d' -i $BMPMAI

        # restart bearmail if needed
        if [ "$BEARMAIL_ON" -eq "1" ] ; then
          echo "Restarting bearmail"
          bearmail-switch on
        fi
}


case "$1" in
    upgrade)
        ;;
    deconfigure)
        ;;
    remove)
        remove_section ;;
    failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1 ;;
esac
#DEBHELPER#
exit 0
